# Generated by Django 5.0.3 on 2024-04-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frost_resistance', models.CharField(max_length=10)),
                ('water_resistance', models.CharField(max_length=10)),
                ('mobility', models.CharField(max_length=10)),
                ('price', models.FloatField()),
            ],
        ),
    ]
